# Generated by Django 4.1.2 on 2022-10-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='email',
            new_name='emmail',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='pasword',
        ),
    ]
