# Generated by Django 4.1.2 on 2022-10-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe', '0002_rename_email_login_emmail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='emmail',
            field=models.EmailField(max_length=20),
        ),
    ]
