# Generated by Django 4.1.2 on 2022-10-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe', '0003_alter_login_emmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('pasword', models.CharField(max_length=10)),
            ],
        ),
    ]
