# Generated by Django 4.1.2 on 2022-10-29 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe', '0004_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='pasword',
            new_name='password',
        ),
    ]
