# Generated by Django 4.1.2 on 2022-10-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe', '0005_rename_pasword_signup_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='nom',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
