# Generated by Django 4.1.2 on 2022-10-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe', '0006_alter_signup_email_alter_signup_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
