# Generated by Django 4.1.2 on 2022-10-29 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe', '0008_rename_nom_signup_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
