# Generated by Django 4.1.2 on 2022-11-05 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionpfe', '0011_remove_demandestagebinome_binome2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandestagebinome',
            name='binome1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
