# Generated by Django 4.1.2 on 2022-11-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe', '0012_alter_demandestagebinome_binome1'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandestagebinome',
            name='type',
            field=models.CharField(default='binome', max_length=255),
        ),
        migrations.AddField(
            model_name='demandestagemonome',
            name='type',
            field=models.CharField(default='monome', max_length=255),
        ),
    ]
