# Generated by Django 4.1.2 on 2022-12-03 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionpfe', '0014_remove_demandestagebinome_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CahierdeCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('besoinsf', models.CharField(max_length=25)),
                ('delais', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('mail', models.EmailField(choices=[('3', 'sywarkhe@gmail.com'), ('2', 'khemirsywar1@gmail.com'), ('1', 'Malakbenali17@gmail.com')], default='1', max_length=255)),
                ('file1', models.FileField(max_length=254, upload_to=None)),
                ('file2', models.FileField(max_length=254, upload_to=None)),
                ('userr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
