# Generated by Django 4.1.2 on 2022-12-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe', '0022_alter_cahiercharge_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cahiercharge',
            name='mail',
            field=models.EmailField(choices=[('3', 'sywarkhe@gmail.com'), ('2', 'khemirsywar1@gmail.com'), ('1', 'Malakbenali17@gmail.com')], default='1', max_length=255),
        ),
    ]
