# Generated by Django 4.1.2 on 2022-12-03 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe', '0023_alter_cahiercharge_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cahiercharge',
            name='mail',
        ),
        migrations.CreateModel(
            name='Encadrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('encadrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpfe.cahiercharge')),
            ],
        ),
    ]
