# Generated by Django 4.1.2 on 2022-12-03 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionpfe', '0024_remove_cahiercharge_mail_encadrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encadrant',
            name='encadrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
