# Generated by Django 4.1.2 on 2022-12-03 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe', '0025_alter_encadrant_encadrant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encadrant',
            name='encadrant',
        ),
        migrations.AddField(
            model_name='cahiercharge',
            name='encadrant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestionpfe.encadrant'),
            preserve_default=False,
        ),
    ]
