# Generated by Django 4.1.2 on 2022-12-04 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionpfe', '0026_remove_encadrant_encadrant_cahiercharge_encadrant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encadrant',
            name='mail',
        ),
        migrations.AddField(
            model_name='encadrant',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='encadrant', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
