# Generated by Django 4.1.2 on 2022-12-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe', '0027_remove_encadrant_mail_encadrant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encadrant',
            name='user',
        ),
        migrations.AddField(
            model_name='encadrant',
            name='mail',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
