# Generated by Django 4.1.2 on 2022-12-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe', '0028_remove_encadrant_user_encadrant_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cahiercharge',
            name='file1',
            field=models.FileField(upload_to='doc/'),
        ),
        migrations.AlterField(
            model_name='cahiercharge',
            name='file2',
            field=models.FileField(upload_to='doc/'),
        ),
    ]
