# Generated by Django 4.1.2 on 2022-12-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe', '0032_alter_cahiercharge_file1_alter_cahiercharge_file2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cahiercharge',
            name='file1',
            field=models.ImageField(default='', upload_to='photos'),
        ),
    ]
