# Generated by Django 4.1.2 on 2022-12-05 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionpfe', '0033_alter_cahiercharge_file1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cahiercharge',
            name='file1',
            field=models.FileField(upload_to='photos'),
        ),
        migrations.CreateModel(
            name='ficherecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binom1', models.CharField(max_length=255)),
                ('binom2', models.CharField(max_length=255)),
                ('parcoursb1', models.CharField(max_length=255)),
                ('parcoursb2', models.CharField(max_length=255)),
                ('nomsociete', models.CharField(max_length=255)),
                ('domainesociete', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('salle', models.CharField(max_length=255)),
                ('nomencadrant', models.CharField(max_length=255)),
                ('nomrapporteur', models.CharField(max_length=255)),
                ('nompresident', models.CharField(max_length=255)),
                ('userr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
