# Generated by Django 4.1.2 on 2022-12-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe', '0034_alter_cahiercharge_file1_ficherecap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficherecap',
            old_name='date',
            new_name='datesoutenance',
        ),
    ]
