# Generated by Django 4.1.2 on 2022-12-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe', '0035_rename_date_ficherecap_datesoutenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficherecap',
            name='Intitule',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficherecap',
            name='typestage',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
