# Generated by Django 4.1.2 on 2022-12-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpfe', '0036_ficherecap_intitule_ficherecap_typestage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficherecap',
            old_name='userr',
            new_name='etudiant',
        ),
    ]
